name: sout_salah
description: "A comprehensive Islamic app for Quran recitations and prayer times."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^8.0.1
  internet_connection_checker: ^3.0.1
  logger: ^2.6.2
  lucide_icons: ^0.257.0
  supabase_flutter: ^2.12.0
  file_picker: ^8.1.6
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  on_audio_query: ^2.9.0
  permission_handler: ^12.0.1
  just_audio_background: ^0.0.1-beta.17
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  crypto: ^3.0.3
  dio: ^5.9.1
  url_launcher: ^6.2.5
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#8ad38c"
  image: assets/splash.png
  android: true
  ios: true

  android_12:
    image: assets/splash.png
    color: "#8ad38c"
    icon_background_color: "#8ad38c"


flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/splash.png